server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/football_app
    username: postgres
    password: nikola
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect